setup: true
version: 2.1
orbs:
  continuation: circleci/continuation@1.0.0
workflows:
  setup:
    jobs:
      - continuation/continue:
          configuration_path: ".circleci/on_pr.yml"
          parameters: /home/circleci/params.json
          pre-steps:
            - run:
                name: Setup params
                command: touch ./circleci/params.json
            - run:
                name: Install jq
                command: sudo apt-get update && sudo apt-get install -y jq
            - run:
                name: Set Pipeline Parameters
                command: |
                  echo ${CIRCLE_PULL_REQUEST}
                  if [ -n "${CIRCLE_PULL_REQUEST}" ]; then
                    PR_NUMBER=$(echo "${CIRCLE_PULL_REQUEST}" | sed 's#.*/pull/##')
                    DESTINATION_BRANCH=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
                      https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${PR_NUMBER} | \
                      jq -r '.base.ref')
                    if [[ "${DESTINATION_BRANCH}" == "dev" || "${DESTINATION_BRANCH}" == "staging" || "${DESTINATION_BRANCH}" == "master" ]]; then
                      IS_PR=true
                    else
                      IS_PR=false
                    fi
                    echo '{ "is_pr": '${IS_PR}', "destination_branch": "'${DESTINATION_BRANCH}'" }' > ./circleci/params.json
                  else
                    echo '{ "is_pr": false }' > ./circleci/params.json
                    cat ./circleci/params.json 
                  fi
