version: 2.1

parameters:
  is_pr:
    type: boolean
    default: false
  destination_branch:
    type: string
    default: ""

executors:
  py-ex:
    docker:
      - image: circleci/python:3.12
    working_directory: ~/repo

jobs:
  lint:
    executor: py-exe
    steps:
      - checkout
      - run:
          name: Install deps
          command: |
            pip install -r requirements.txt
      - run:
          name: lint
          command: |
            if flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics | grep -q "0"; then
              echo "Lint has passed and ready to merge"
            else
              echo "Lint failed, fix the issues"
              exit 1
            fi
      - run:
          name: Linting✅
          command: echo "Linting completed"

  test:
    executor: py-ex
    steps:
      - checkout
      - run:
        name: Install deps
        command: |
          pip install -r requirements.txt
      # - run:
      #     name: Run Tests
      #     command: |
      #       if pytest; then
      #         echo "Tests complete."
      #       else
      #         echo "No tests found."
      - run:
        name: tests
        command: |
          echo "Testing is done"
      - run:
        name: slack notification
        command: |
          echo "Sending notification is slack!"

  pr_comment-fail:
    executor: py-ex
    steps:
      - run:
          name: Add Comment to PR
          command: |
            curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" \
            -d '{"body":"PR failed on this stage: ${CIRCLE_STAGE} - [Job link](${CIRCLE_BUILD_URL})"}' \
            https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/issues/${CIRCLE_PR_NUMBER}/comments

workflows:
  version: 2.1
  lint_and_test_workflow:
    when: << pipeline.parameters.is_pr >>
    jobs:
      - lint:
      - test:
          requires:
            - lint
      - pr_comment-fail:
          requires:
            - lint
            - test
          when: on_fail
